# Site settings
title: Orlando Devs
email: orlandodevcommunity@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Official account for the Orlando Devs Community!
  We are an inclusive community, open to everyone who has a passion in software
  development in the Orlando area.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://orlandodevs.com" # the base hostname & protocol for your site
twitter_username: OrlandoDevs
github_username:  OrlandoDevs

# Open Graph meta tags
og:
  image: /assets/odevs-helmet.png

# Build settings
markdown: kramdown

kramdown:
  input: GFM

# Fetch the latest speaker data from socrata API
jekyll_get:
  data: speakers
  json: 'https://opendata.socrata.com/resource/hzvk-fgsu.json?$order=date%20DESC'
  cache: true

# Outputting
permalink:     /blog/:title/
paginate_path: /page:num
timezone:      null
